// ── BNAIQ Central Data Store ──
// Single source of truth for all pages.

window.BNAIQ = window.BNAIQ || {};

// ────────────────────────────────────────────────
// SUBSCRIPTION PLANS
// ────────────────────────────────────────────────
BNAIQ.PLANS = [
  {
    id: 'free',
    name: 'Basic',
    price: 0,
    period: 'Forever',
    badge: null,
    color: '#8A8880',
    features: [
      'Company profile listing',
      'Up to 3 active projects',
      'Standard search visibility',
      'Client inquiry inbox',
      'BNAIQ badge (unverified)',
    ],
    limits: { projects: 3, blueprints: 5, teamMembers: 1 },
    cta: 'Get Started Free',
  },
  {
    id: 'pro',
    name: 'Pro',
    price: 499,
    period: 'per month',
    badge: 'Most Popular',
    color: '#C9A84C',
    features: [
      'Everything in Basic',
      'Up to 25 active projects',
      'RTA verification badge',
      'Blueprint vault (50GB)',
      'Investor progress tracker',
      'Priority search placement',
      'Analytics dashboard',
      '3 team members',
    ],
    limits: { projects: 25, blueprints: 50, teamMembers: 3 },
    cta: 'Start Pro Trial',
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    price: 1899,
    period: 'per month',
    badge: 'RTA Ready',
    color: '#52C07A',
    features: [
      'Everything in Pro',
      'Unlimited projects',
      'RTA / DM API integration',
      'Government portal access',
      'Unlimited blueprint vault',
      'White-label investor portal',
      'Dedicated account manager',
      'Unlimited team members',
      'SLA 99.9% uptime',
      'Audit log export (GDPR)',
    ],
    limits: { projects: Infinity, blueprints: Infinity, teamMembers: Infinity },
    cta: 'Contact Sales',
  },
];

// ────────────────────────────────────────────────
// COMPANIES
// ────────────────────────────────────────────────
BNAIQ.COMPANIES = [
  {
    id: 'c1', name: 'Al Fardan Construction LLC', category: 'commercial',
    emoji: '🏢', location: 'Dubai Marina', projects: 47, rating: 4.9,
    reviews: 124, founded: 2008, verified: true, plan: 'enterprise',
    specialties: ['High-Rise', 'Commercial', 'Mixed-Use'],
    license: 'DM-CON-2008-447',
    desc: 'Premium commercial construction with 15+ years of landmark projects across Dubai and Abu Dhabi.',
    coverColor: '#1a2a3a',
  },
  {
    id: 'c2', name: 'GoldenBuild Renovations', category: 'renovation',
    emoji: '🔨', location: 'Business Bay', projects: 312, rating: 4.8,
    reviews: 88, founded: 2014, verified: true, plan: 'pro',
    specialties: ['Renovation', 'Fit-Out', 'Interior'],
    license: 'DM-REN-2014-891',
    desc: 'End-to-end renovation specialists for residential and commercial spaces.',
    coverColor: '#1a1a2a',
  },
  {
    id: 'c3', name: 'Nakheel Infrastructure Partners', category: 'infrastructure',
    emoji: '🌉', location: 'Deira', projects: 28, rating: 5.0,
    reviews: 41, founded: 2006, verified: true, plan: 'enterprise',
    specialties: ['Infrastructure', 'Roads', 'Civil'],
    license: 'DM-INF-2006-112',
    desc: 'Large-scale civil and infrastructure works across Dubai emirate.',
    coverColor: '#1a2a1a',
  },
  {
    id: 'c4', name: 'Skyline Villas & Homes', category: 'residential',
    emoji: '🏠', location: 'Palm Jumeirah', projects: 89, rating: 4.7,
    reviews: 203, founded: 2011, verified: true, plan: 'pro',
    specialties: ['Villas', 'Townhouses', 'Residential'],
    license: 'DM-RES-2011-334',
    desc: 'Luxury residential construction specializing in bespoke villas and townhouses.',
    coverColor: '#2a1a1a',
  },
  {
    id: 'c5', name: 'Element Interiors Dubai', category: 'interior',
    emoji: '🛋️', location: 'DIFC', projects: 156, rating: 4.6,
    reviews: 317, founded: 2016, verified: true, plan: 'pro',
    specialties: ['Interior Design', 'Fit-Out', 'FF&E'],
    license: 'DM-INT-2016-779',
    desc: 'Award-winning interior fit-out and FF&E procurement for premium projects.',
    coverColor: '#2a1a2a',
  },
  {
    id: 'c6', name: 'Axis MEP Engineering', category: 'commercial',
    emoji: '⚙️', location: 'JLT', projects: 71, rating: 4.8,
    reviews: 96, founded: 2010, verified: true, plan: 'pro',
    specialties: ['MEP', 'HVAC', 'Electrical'],
    license: 'DM-MEP-2010-556',
    desc: 'Mechanical, electrical, and plumbing specialists for commercial and industrial.',
    coverColor: '#1a1e2a',
  },
  {
    id: 'c7', name: 'ArchForm Design Studio', category: 'interior',
    emoji: '🎨', location: 'DIFC', projects: 92, rating: 4.9,
    reviews: 143, founded: 2017, verified: true, plan: 'pro',
    specialties: ['Architecture', 'Interior', '3D Design'],
    license: 'DM-ARC-2017-441',
    desc: 'Boutique architectural and interior design studio for luxury residential and hospitality.',
    coverColor: '#1e1a2a',
  },
  {
    id: 'c8', name: 'CrestBuild Residential', category: 'residential',
    emoji: '🏡', location: 'Palm Jumeirah', projects: 134, rating: 4.6,
    reviews: 228, founded: 2009, verified: true, plan: 'pro',
    specialties: ['Villas', 'Swimming Pools', 'Landscaping'],
    license: 'DM-RES-2009-198',
    desc: 'Premium villa and luxury residential construction with full fit-out capability.',
    coverColor: '#2a1e1a',
  },
  {
    id: 'c9', name: 'Urban Steel & Structures', category: 'commercial',
    emoji: '🔩', location: 'Deira', projects: 39, rating: 4.4,
    reviews: 62, founded: 2007, verified: true, plan: 'free',
    specialties: ['Structural Steel', 'Warehouses', 'Industrial'],
    license: 'DM-STR-2007-310',
    desc: 'Structural steel fabrication and erection for commercial and industrial builds.',
    coverColor: '#1e2020',
  },
  {
    id: 'c10', name: 'GreenSpace Landscaping', category: 'renovation',
    emoji: '🌿', location: 'JLT', projects: 280, rating: 4.7,
    reviews: 119, founded: 2015, verified: true, plan: 'free',
    specialties: ['Landscaping', 'Irrigation', 'Outdoor'],
    license: 'DM-GRN-2015-662',
    desc: 'Full-service landscaping and outdoor design for residential and commercial.',
    coverColor: '#141e14',
  },

  {
    id: 'c11', name: 'Binghatti Emerald', category: 'residential',
    emoji: '💎', location: 'JVC', projects: 1, rating: 4.9,
    reviews: 62, founded: 2022, verified: true, plan: 'enterprise',
    specialties: ['Residential', 'High-Rise', 'Investor Tracker'],
    license: 'DM-DEV-2022-404',
    desc: 'Binghatti Emerald live project tracker with progress, floors, milestones and investor updates.',
    coverColor: '#0d2a22',
  },
];

// ────────────────────────────────────────────────
// PROJECTS (with investor-facing progress data)
// ────────────────────────────────────────────────
BNAIQ.PROJECTS = [

  {
    id: 'p99', companyId: 'c11',
    name: 'Binghatti Emerald',
    type: 'Residential High-Rise',
    location: 'JVC, Dubai',
    value: 'AED 300M',
    valueRaw: 300000000,
    startDate: '2023-01-01',
    endDate: '2026-01-01',
    status: 'active',
    totalFloors: 23,
    completedFloors: 10,
    progressPct: 43,
    emoji: '💎',
    coverColor: '#08362c',
    description: 'Live project tracker for Binghatti Emerald with floor progress, milestones, updates, and investor-facing construction visibility.',
    milestones: [
      { name: 'Foundation', done: true, date: '2023-05-01', pct: 100 },
      { name: 'Podium Structure', done: true, date: '2023-12-01', pct: 100 },
      { name: 'Tower Structure', done: false, date: '2025-06-01', pct: 45 },
      { name: 'MEP & Façade', done: false, date: '2025-10-01', pct: 20 },
      { name: 'Handover', done: false, date: '2026-01-01', pct: 0 },
    ],
    updates: [
      { date: '2025-05-01', text: 'Live tracker page added for demo. Progress data can be changed later.' },
      { date: '2025-04-20', text: 'Floor progress and milestone dashboard prepared.' },
    ],
    investors: ['Demo Investor Group'],
    budget: { total: 300, spent: 129, currency: 'AED M' },
  },
  {
    id: 'p1', companyId: 'c1',
    name: 'Horizon Tower — Business Bay',
    type: 'High-Rise Commercial',
    location: 'Business Bay, Dubai',
    value: 'AED 480M',
    valueRaw: 480000000,
    startDate: '2023-03-01',
    endDate: '2026-06-01',
    status: 'active',
    totalFloors: 42,
    completedFloors: 18,
    progressPct: 43,
    emoji: '🏢',
    coverColor: '#0d1b2a',
    description: 'A landmark 42-floor mixed-use tower featuring Grade A office space, premium retail podium, and sky-lounge facilities. Delivered to full Dubai Municipality green-building standards.',
    milestones: [
      { name: 'Foundation & Piling',      done: true,  date: '2023-06-15', pct: 100 },
      { name: 'Basement Structure',        done: true,  date: '2023-09-20', pct: 100 },
      { name: 'Ground + Podium Floors',    done: true,  date: '2024-02-10', pct: 100 },
      { name: 'Tower Core (Floors 1-18)', done: true,  date: '2024-11-30', pct: 100 },
      { name: 'Tower Structure (19-30)',   done: false, date: '2025-06-30', pct: 35  },
      { name: 'Tower Structure (31-42)',   done: false, date: '2025-12-01', pct: 0   },
      { name: 'MEP Rough-In',              done: false, date: '2026-02-01', pct: 20  },
      { name: 'Fit-Out & Façade',          done: false, date: '2026-04-15', pct: 0   },
      { name: 'Handover',                  done: false, date: '2026-06-01', pct: 0   },
    ],
    updates: [
      { date: '2025-04-28', text: 'Floor 18 slab pour completed. Structural inspection passed. Moving to floor 19 formwork.' },
      { date: '2025-04-01', text: 'MEP rough-in started on floors 5–10. Electrical conduit installation 60% complete.' },
      { date: '2025-03-15', text: 'Curtain wall glazing commenced on floors 1–6. Structural steel for floors 15–18 erected.' },
    ],
    investors: ['Mohammed Al Rashid', 'Dubai Capital Partners', 'Emaar Investments'],
    budget: { total: 480, spent: 206, currency: 'AED M' },
  },
  {
    id: 'p2', companyId: 'c1',
    name: 'Al Barsha Medical Center Expansion',
    type: 'Healthcare',
    location: 'Al Barsha, Dubai',
    value: 'AED 120M',
    valueRaw: 120000000,
    startDate: '2022-01-10',
    endDate: '2024-08-01',
    status: 'complete',
    totalFloors: 8,
    completedFloors: 8,
    progressPct: 100,
    emoji: '🏥',
    coverColor: '#0a1a14',
    description: 'Eight-floor medical center expansion including specialist clinics, surgical suites, and diagnostic imaging. Delivered on time and on budget.',
    milestones: [
      { name: 'Foundation',          done: true, date: '2022-04-01', pct: 100 },
      { name: 'Structure Complete',  done: true, date: '2022-10-15', pct: 100 },
      { name: 'MEP Installation',    done: true, date: '2023-04-20', pct: 100 },
      { name: 'Fit-Out',             done: true, date: '2023-11-01', pct: 100 },
      { name: 'Commissioning',       done: true, date: '2024-05-15', pct: 100 },
      { name: 'Handover',            done: true, date: '2024-08-01', pct: 100 },
    ],
    updates: [
      { date: '2024-08-01', text: 'Project fully handed over to DHA. Certificate of completion issued. All snagging cleared.' },
    ],
    investors: ['Dubai Health Authority', 'Private Health Fund LLC'],
    budget: { total: 120, spent: 118, currency: 'AED M' },
  },
  {
    id: 'p3', companyId: 'c3',
    name: 'Sheikh Zayed Road Underpass — Phase 2',
    type: 'Infrastructure / Civil',
    location: 'Sheikh Zayed Road, Dubai',
    value: 'AED 1.1B',
    valueRaw: 1100000000,
    startDate: '2024-01-01',
    endDate: '2027-03-01',
    status: 'active',
    totalFloors: 0,
    completedFloors: 0,
    progressPct: 22,
    emoji: '🌉',
    coverColor: '#0d1a0d',
    description: 'Major road infrastructure project: 3.2km underpass, 4-lane dual carriageway with smart traffic integration, and pedestrian bridges. RTA-contracted.',
    milestones: [
      { name: 'Enabling Works & Survey',   done: true,  date: '2024-03-01', pct: 100 },
      { name: 'Excavation Phase 1',        done: true,  date: '2024-09-01', pct: 100 },
      { name: 'Excavation Phase 2',        done: false, date: '2025-06-01', pct: 55  },
      { name: 'Structural Concrete Works', done: false, date: '2025-12-01', pct: 10  },
      { name: 'Road Surfacing',            done: false, date: '2026-06-01', pct: 0   },
      { name: 'Smart Systems Install',     done: false, date: '2026-12-01', pct: 0   },
      { name: 'Testing & Commissioning',   done: false, date: '2027-02-01', pct: 0   },
      { name: 'Handover to RTA',           done: false, date: '2027-03-01', pct: 0   },
    ],
    updates: [
      { date: '2025-04-20', text: 'Excavation Phase 2 progressing on schedule. 1.8km of 3.2km total length excavated.' },
      { date: '2025-03-01', text: 'Utility diversion completed on Section A. Dewatering system operational across full site.' },
    ],
    investors: ['RTA Dubai', 'UAE Infrastructure Fund'],
    budget: { total: 1100, spent: 242, currency: 'AED M' },
  },
  {
    id: 'p4', companyId: 'c4',
    name: 'Palm Frond Villa — Plot J-14',
    type: 'Luxury Residential Villa',
    location: 'Palm Jumeirah, Dubai',
    value: 'AED 22M',
    valueRaw: 22000000,
    startDate: '2024-08-01',
    endDate: '2025-12-01',
    status: 'active',
    totalFloors: 3,
    completedFloors: 1,
    progressPct: 38,
    emoji: '🏠',
    coverColor: '#1a0d0d',
    description: 'Bespoke 3-floor luxury villa on Palm Jumeirah. Ground floor entertainment, first floor living, second floor master suites. Private pool and landscaped garden.',
    milestones: [
      { name: 'Design & Permits',       done: true,  date: '2024-08-20', pct: 100 },
      { name: 'Foundation',             done: true,  date: '2024-10-15', pct: 100 },
      { name: 'Ground Floor Structure', done: true,  date: '2025-01-20', pct: 100 },
      { name: '1st Floor Structure',    done: false, date: '2025-04-01', pct: 70  },
      { name: '2nd Floor Structure',    done: false, date: '2025-06-15', pct: 0   },
      { name: 'Roof & Waterproofing',   done: false, date: '2025-08-01', pct: 0   },
      { name: 'MEP & Fit-Out',          done: false, date: '2025-10-01', pct: 0   },
      { name: 'Landscaping & Pool',     done: false, date: '2025-11-15', pct: 0   },
      { name: 'Handover',               done: false, date: '2025-12-01', pct: 0   },
    ],
    updates: [
      { date: '2025-04-25', text: '1st floor columns and beams erected. Slab formwork 70% complete. On schedule for pour next week.' },
      { date: '2025-03-20', text: 'Ground floor MEP rough-in completed. External blockwork 100% done.' },
    ],
    investors: ['Private Client'],
    budget: { total: 22, spent: 8.4, currency: 'AED M' },
  },
  {
    id: 'p5', companyId: 'c2',
    name: 'DIFC Gate Avenue Fit-Out — Retail Block C',
    type: 'Commercial Fit-Out',
    location: 'DIFC, Dubai',
    value: 'AED 34M',
    valueRaw: 34000000,
    startDate: '2025-01-15',
    endDate: '2025-09-01',
    status: 'active',
    totalFloors: 2,
    completedFloors: 0,
    progressPct: 28,
    emoji: '🏪',
    coverColor: '#1a1020',
    description: 'Full fit-out of 4,200sqm retail and F&B block at DIFC Gate Avenue. Includes MEP, joinery, FF&E, and technology fit-out for 12 retail units.',
    milestones: [
      { name: 'Design Freeze',            done: true,  date: '2025-01-30', pct: 100 },
      { name: 'Demolition & Strip-Out',   done: true,  date: '2025-02-15', pct: 100 },
      { name: 'MEP First Fix',            done: false, date: '2025-04-30', pct: 60  },
      { name: 'Drywall & Ceilings',       done: false, date: '2025-05-31', pct: 20  },
      { name: 'MEP Second Fix',           done: false, date: '2025-06-30', pct: 0   },
      { name: 'Joinery & FF&E',           done: false, date: '2025-07-31', pct: 0   },
      { name: 'Snagging & Handover',      done: false, date: '2025-09-01', pct: 0   },
    ],
    updates: [
      { date: '2025-04-29', text: 'MEP first fix 60% complete across all units. HVAC ducting installed in units 1-8.' },
      { date: '2025-04-10', text: 'Demolition works 100% complete. Site hoarding removed from Gate Avenue frontage.' },
    ],
    investors: ['DIFC Retail Investors LLC', 'Gate Avenue Development'],
    budget: { total: 34, spent: 9.5, currency: 'AED M' },
  },
  {
    id: 'p6', companyId: 'c6',
    name: 'JVC Residential Complex — MEP Package',
    type: 'MEP Engineering',
    location: 'Jumeirah Village Circle, Dubai',
    value: 'AED 18M',
    valueRaw: 18000000,
    startDate: '2024-11-01',
    endDate: '2026-02-01',
    status: 'active',
    totalFloors: 14,
    completedFloors: 5,
    progressPct: 34,
    emoji: '⚙️',
    coverColor: '#0a0d1a',
    description: 'Full MEP package for 14-floor residential tower in JVC. Includes HVAC, plumbing, electrical, fire alarm, BMS, and ELV systems.',
    milestones: [
      { name: 'Shop Drawings Approved',    done: true,  date: '2024-12-01', pct: 100 },
      { name: 'Basement MEP',              done: true,  date: '2025-01-15', pct: 100 },
      { name: 'Ground to Floor 5 MEP',    done: true,  date: '2025-03-30', pct: 100 },
      { name: 'Floor 6-10 MEP',           done: false, date: '2025-07-01', pct: 40  },
      { name: 'Floor 11-14 MEP',          done: false, date: '2025-10-01', pct: 0   },
      { name: 'Testing & Commissioning',  done: false, date: '2026-01-01', pct: 0   },
      { name: 'Handover',                 done: false, date: '2026-02-01', pct: 0   },
    ],
    updates: [
      { date: '2025-04-22', text: 'Floor 6-8 HVAC ducting 40% complete. Plumbing rough-in on track for floors 6-7.' },
      { date: '2025-03-30', text: 'Floors 1-5 MEP 100% complete. DM inspection passed all systems.' },
    ],
    investors: ['Nakheel Properties', 'JVC Residential Fund'],
    budget: { total: 18, spent: 6.1, currency: 'AED M' },
  },
];

// Helper: get company by id
BNAIQ.getCompany = id => BNAIQ.COMPANIES.find(c => c.id === id);
BNAIQ.getProject = id => BNAIQ.PROJECTS.find(p => p.id === id);
BNAIQ.getCompanyProjects = cid => BNAIQ.PROJECTS.filter(p => p.companyId === cid);